### ISSUE TITLE
Updater.js gives 0x00000NAN

### ISSUE THREAD

**Issue by nightlark** [noggaholic/machinima-studio#1]
With one (or more) of the latest patches it looks like the search pattern used to find camera.original, player.original, and environment.fog.original have been changed - some comments on where to look for a new search pattern for these and other pointers would be useful. I suspect things like the base pointer for the mouse could  have also changed, and offsets within objects have the potential to change, even if it is infrequently.

**Comment by karliky** [comment]
I've manually updated all the offsets so you can download again the latest release from here:

commit: https://github.com/karliky/machinima-studio/commit/62af9daa5afd0d4eb800749278ff1f855dcaba87

release: https://github.com/karliky/machinima-studio/archive/1.0.zip

It's true that 3 patterns are not working, I have to figure out how to solve it. thank you!

**Comment by nightlark** [comment]
Entering spectator mode caused a crash with the offsets used in commit 62af9da.
I switched offsets for the 8 patches and player movement to the ones given by the updater and it seemed to be fully functional. That said they pushed another patch just now, which may have changed the offsets again.

patch_1: 0x0067572A
patch_2: 0x00675658
patch_3: 0x006755F3
patch_4: 0x0067554C
patch_5: 0x006752F7
patch_6: 0x006752F7
patch_7: 0x00675462
patch_8: 0x00674A72
movement: 0x0065F9A0

**Comment by karliky** [comment]
Oooops, yes, they usually release small hot fixes after an official patch, I have to manually update the offsets again

**Comment by karliky** [comment]
Just published a release with the new offsets https://github.com/karliky/machinima-studio/archive/2.zip
